config/routes.rb
MusicRights::Application.routes.draw do
  devise_for :users

  resources :songs
  

end

app/models/song.rb
class Song < ActiveRecord::Base
  has_attached_file :song,
#        :path => ":rails_root/public/:basename.:extension"
        :storage => :s3,
        :s3_credentials => "#{RAILS_ROOT}/config/s3_config.yaml",
        :path => ":attachment/:id/:style.:extension",
        :bucket => 'music-rights-media'

  # Acts as taggable on
  acts_as_taggable

  # Paperclip Validations
  validates_attachment_presence :song
  validates_attachment_content_type :song, :content_type => [ 'application/mp3', 'application/x-mp3', 'audio/mpeg', 'audio/mp3' ]
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.xml
  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @songs }
    end
  end

  # GET /songs/1
  # GET /songs/1.xml
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.xml
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.xml
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to(@song, :notice => 'Song was successfully created.') }
        format.xml  { render :xml => @song, :status => :created, :location => @song }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.xml
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to(@song, :notice => 'Song was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @song.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.xml
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to(songs_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/songs/_form.html.erb
<% content_for :dom_loaded do %>
  <%= load_uploadify %>

  $("#song_song").uploadify({
    'uploader'       : '/flash/uploadify.swf',
    'buttonImg'      : '/images/upload.png',
    'cancelImg'      : '/images/cancel.png',
    'script'         : S3_BUCKET,
    'fileDataName'   : 'file',
    'scriptData'     : TRACK_UPLOADIFY,
    'fileDesc'       : 'Music',
    'fileExt'        : '*.mp3;', //list of uploadable filetypes
    'onComplete'     : uploadify_complete,
    'onError'        : uploadify_error,
    'scriptAccess'   : 'always',
    'queueID'        : 'uploadifyQueue',
    'auto'           : true,
    'folder'         : '',
    'sizeLimit'      : 31457280,
    'multi'          : true
  });

  function uploadify_error(event, queueID, fileObj, errorObj){
    if(errorObj.info == 201){
      $.post(CALLBACK_URL, {'_method': 'put', 'file[size]': fileObj.size, 'file[name]': fileObj.name}, function(data){
        //  do stuff with data
        $('#song_song').uploadifyCancel(queueID);
        }, 'json');
    }
    return true;
  }

  function uploadify_complete(event, queueID, fileObj, response){
    $.post(CALLBACK_URL, {'_method': 'put', 'file[size]': fileObj.size, 'file[name]': fileObj.name}, function(data){
      // do stuff with data
      }, 'json');
  }
<% end %>

<%= form_for(@song, :html => { :multipart => true }) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :song %><br />
    <%= f.file_field :song %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<h1>Listing songs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Song file name</th>
    <th>Song content type</th>
    <th>Song file size</th>
    <th>Song updated at</th>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @songs.each do |song| %>
  <tr>
    <td><%= song.name %></td>
    <td><%= song.song_file_name %></td>
    <td><%= song.song_content_type %></td>
    <td><%= song.song_file_size %></td>
    <td><%= song.song_updated_at %></td>
    <td><%= song.category_id %></td>
    <td><%= link_to 'Show', song %></td>
    <td><%= link_to 'Edit', edit_song_path(song) %></td>
    <td><%= link_to 'Destroy', song, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @song.name %>
</p>

<p>
  <b>Song file name:</b>
  <%= @song.song_file_name %>
</p>

<p>
  <b>Song content type:</b>
  <%= @song.song_content_type %>
</p>

<p>
  <b>Song file size:</b>
  <%= @song.song_file_size %>
</p>

<p>
  <b>Song updated at:</b>
  <%= @song.song_updated_at %>
</p>

<p>
  <b>Category:</b>
  <%= @song.category_id %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>